services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: autoscaler
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  forecaster:
    image: ghcr.io/aau-p9s/forecaster:test
    restart: always
    environment:
      FORECASTER__PGSQL__DATABASE: autoscaler
      FORECASTER__PGSQL__USER: root
      FORECASTER__PGSQL__PASSWORD: password
      FORECASTER__PGSQL__ADDR: db
      FORECASTER__PGSQL__PORT: 5432
      FORECASTER__ADDR: 0.0.0.0
      FORECASTER__PORT: 8080
    ports:
      - "8080:8080"

    depends_on:
      - db
